apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: als
  annotations:
    build: "20250609_233845"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        build: "20250609_233845"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: server
          image: alpine:3.22.0
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -e
              addgroup -g 1000 als
              adduser -u 1000 -G als -D als
              apk add --no-cache git gosu
              git clone https://github.com/wsva/als_server_build
              chown -R als:als /home/als/als_server
              gosu als ./als_server/als_server
          ports:
            - containerPort: 443
          volumeMounts:
            - name: ssl
              mountPath: /ssl
            - name: docs
              mountPath: /docs
      volumes:
        - name: ssl
          hostPath:
            path: /als/ssl
            type: Directory
        - name: docs
          hostPath:
            path: /docs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: als
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - port: 443
      targetPort: 443
      nodePort: 1235